# Simple sample configuration file for Okapi Hazelcast clustering
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast
  namespace: "okapi-cluster-demo"
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- note the schema must match the version of Hazelcast in
         the version of Vert.X in Okapi -->
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.hazelcast.com/schema/config
               https://www.hazelcast.com/schema/config/hazelcast-config-4.2.xsd">

      <cluster-name>okapi-cluster-demo</cluster-name>

      <network>
        <join>
          <kubernetes enabled="true">
            <namespace>okapi-cluster-demo</namespace>
            <service-name>okapi</service-name>
          </kubernetes>
        </join>
      </network>

      <!-- defaults from vertx default-cluster.xml -->
      <multimap name="__vertx.subs">
        <backup-count>1</backup-count>
        <value-collection-type>SET</value-collection-type>
      </multimap>

      <map name="__vertx.haInfo">
        <backup-count>1</backup-count>
      </map>

      <map name="__vertx.nodeInfo">
        <backup-count>1</backup-count>
      </map>

      <cp-subsystem>
        <cp-member-count>0</cp-member-count>
        <semaphores>
          <semaphore>
            <name>__vertx.*</name>
            <jdk-compatible>false</jdk-compatible>
            <initial-permits>1</initial-permits>
          </semaphore>
        </semaphores>
      </cp-subsystem>

    </hazelcast>
